name: test-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
