name: test-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
      - name: name
        run: echo "${{ github.actor }}"
